name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        accountID: ${{ secrets.ACCOUNT_ID }}
        apikey: ${{ secrets.API_KEY }}
      run: terraform plan -var="accountID=$accountID" -var="apikey=$apikey" --var-file="workflow.tfvars" --var-file="alerts.tfvars" --var-file="sli.tfvars" 

    - name: Terraform Apply
      env:
        accountID: ${{ secrets.ACCOUNT_ID }}
        apikey: ${{ secrets.API_KEY }}
      run: terraform apply --auto-approve -var="accountID=$accountID" -var="apikey=$apikey" --var-file="workflow.tfvars" --var-file="alerts.tfvars" --var-file="sli.tfvars" 
