name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure Environment Variables
        run: |
          echo "NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "newrelic_account_id=$NEWRELIC_ACCOUNT_ID" -var "newrelic_api_key=$NEWRELIC_API_KEY"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "newrelic_account_id=$NEWRELIC_ACCOUNT_ID" -var "newrelic_api_key=$NEWRELIC_API_KEY"

